export const LIQUID_OPTIONS_UNIVERSE = [
  { symbol: 'SPY', name: 'SPDR S&P 500 ETF', group: 'ETF / index' },
  { symbol: 'QQQ', name: 'Invesco QQQ Trust', group: 'ETF / index' },
  { symbol: 'IWM', name: 'iShares Russell 2000 ETF', group: 'ETF / index' },
  { symbol: 'DIA', name: 'SPDR Dow Jones ETF', group: 'ETF / index' },
  { symbol: 'XLF', name: 'Financial Select Sector SPDR', group: 'ETF / index' },
  { symbol: 'XLK', name: 'Technology Select Sector SPDR', group: 'ETF / index' },
  { symbol: 'XLE', name: 'Energy Select Sector SPDR', group: 'ETF / index' },
  { symbol: 'XLV', name: 'Health Care Select Sector SPDR', group: 'ETF / index' },
  { symbol: 'XLY', name: 'Consumer Discretionary SPDR', group: 'ETF / index' },
  { symbol: 'XLI', name: 'Industrial Select Sector SPDR', group: 'ETF / index' },
  { symbol: 'XLC', name: 'Communication Services SPDR', group: 'ETF / index' },
  { symbol: 'XLP', name: 'Consumer Staples SPDR', group: 'ETF / index' },
  { symbol: 'XLU', name: 'Utilities Select Sector SPDR', group: 'ETF / index' },
  { symbol: 'XLB', name: 'Materials Select Sector SPDR', group: 'ETF / index' },
  { symbol: 'XLRE', name: 'Real Estate Select Sector SPDR', group: 'ETF / index' },
  { symbol: 'SMH', name: 'VanEck Semiconductor ETF', group: 'ETF / index' },
  { symbol: 'SOXX', name: 'iShares Semiconductor ETF', group: 'ETF / index' },
  { symbol: 'AAPL', name: 'Apple', group: 'Technology / growth' },
  { symbol: 'MSFT', name: 'Microsoft', group: 'Technology / growth' },
  { symbol: 'NVDA', name: 'NVIDIA', group: 'Technology / growth' },
  { symbol: 'AMZN', name: 'Amazon', group: 'Technology / growth' },
  { symbol: 'META', name: 'Meta Platforms', group: 'Technology / growth' },
  { symbol: 'GOOGL', name: 'Alphabet Class A', group: 'Technology / growth' },
  { symbol: 'GOOG', name: 'Alphabet Class C', group: 'Technology / growth' },
  { symbol: 'TSLA', name: 'Tesla', group: 'Technology / growth' },
  { symbol: 'AVGO', name: 'Broadcom', group: 'Technology / growth' },
  { symbol: 'AMD', name: 'Advanced Micro Devices', group: 'Technology / growth' },
  { symbol: 'NFLX', name: 'Netflix', group: 'Technology / growth' },
  { symbol: 'ADBE', name: 'Adobe', group: 'Technology / growth' },
  { symbol: 'CRM', name: 'Salesforce', group: 'Technology / growth' },
  { symbol: 'ORCL', name: 'Oracle', group: 'Technology / growth' },
  { symbol: 'INTC', name: 'Intel', group: 'Technology / growth' },
  { symbol: 'QCOM', name: 'Qualcomm', group: 'Technology / growth' },
  { symbol: 'AMAT', name: 'AMAT', group: 'Technology / growth' },
  { symbol: 'MU', name: 'MU', group: 'Technology / growth' },
  { symbol: 'LRCX', name: 'LRCX', group: 'Technology / growth' },
  { symbol: 'TXN', name: 'TXN', group: 'Technology / growth' },
  { symbol: 'NOW', name: 'NOW', group: 'Technology / growth' },
  { symbol: 'PANW', name: 'PANW', group: 'Technology / growth' },
  { symbol: 'CRWD', name: 'CRWD', group: 'Technology / growth' },
  { symbol: 'SNOW', name: 'SNOW', group: 'Technology / growth' },
  { symbol: 'DDOG', name: 'DDOG', group: 'Technology / growth' },
  { symbol: 'MDB', name: 'MDB', group: 'Technology / growth' },
  { symbol: 'SHOP', name: 'SHOP', group: 'Technology / growth' },
  { symbol: 'UBER', name: 'UBER', group: 'Technology / growth' },
  { symbol: 'ABNB', name: 'ABNB', group: 'Technology / growth' },
  { symbol: 'PYPL', name: 'PYPL', group: 'Technology / growth' },
  { symbol: 'SQ', name: 'SQ', group: 'Technology / growth' },
  { symbol: 'COIN', name: 'COIN', group: 'Technology / growth' },
  { symbol: 'PLTR', name: 'PLTR', group: 'Technology / growth' },
  { symbol: 'RBLX', name: 'RBLX', group: 'Financials' },
  { symbol: 'JPM', name: 'JPMorgan Chase', group: 'Financials' },
  { symbol: 'BAC', name: 'Bank of America', group: 'Financials' },
  { symbol: 'WFC', name: 'Wells Fargo', group: 'Financials' },
  { symbol: 'GS', name: 'Goldman Sachs', group: 'Financials' },
  { symbol: 'MS', name: 'Morgan Stanley', group: 'Financials' },
  { symbol: 'C', name: 'C', group: 'Financials' },
  { symbol: 'SCHW', name: 'SCHW', group: 'Financials' },
  { symbol: 'BLK', name: 'BLK', group: 'Financials' },
  { symbol: 'AXP', name: 'AXP', group: 'Financials' },
  { symbol: 'V', name: 'V', group: 'Financials' },
  { symbol: 'MA', name: 'MA', group: 'Financials' },
  { symbol: 'COF', name: 'COF', group: 'Financials' },
  { symbol: 'XOM', name: 'Exxon Mobil', group: 'Financials' },
  { symbol: 'CVX', name: 'Chevron', group: 'Financials' },
  { symbol: 'COP', name: 'COP', group: 'Financials' },
  { symbol: 'SLB', name: 'SLB', group: 'Financials' },
  { symbol: 'EOG', name: 'EOG', group: 'Energy' },
  { symbol: 'OXY', name: 'OXY', group: 'Energy' },
  { symbol: 'HAL', name: 'HAL', group: 'Energy' },
  { symbol: 'KMI', name: 'KMI', group: 'Energy' },
  { symbol: 'LNG', name: 'LNG', group: 'Energy' },
  { symbol: 'UNH', name: 'UnitedHealth', group: 'Energy' },
  { symbol: 'LLY', name: 'Eli Lilly', group: 'Energy' },
  { symbol: 'JNJ', name: 'Johnson & Johnson', group: 'Energy' },
  { symbol: 'MRK', name: 'Merck', group: 'Energy' },
  { symbol: 'ABBV', name: 'AbbVie', group: 'Health care' },
  { symbol: 'PFE', name: 'Pfizer', group: 'Health care' },
  { symbol: 'TMO', name: 'TMO', group: 'Health care' },
  { symbol: 'ABT', name: 'ABT', group: 'Health care' },
  { symbol: 'DHR', name: 'DHR', group: 'Health care' },
  { symbol: 'ISRG', name: 'ISRG', group: 'Health care' },
  { symbol: 'VRTX', name: 'VRTX', group: 'Health care' },
  { symbol: 'REGN', name: 'REGN', group: 'Health care' },
  { symbol: 'MRNA', name: 'MRNA', group: 'Health care' },
  { symbol: 'CVS', name: 'CVS', group: 'Health care' },
  { symbol: 'HUM', name: 'HUM', group: 'Health care' },
  { symbol: 'CI', name: 'CI', group: 'Health care' },
  { symbol: 'NVO', name: 'NVO', group: 'Health care' },
  { symbol: 'HD', name: 'Home Depot', group: 'Health care' },
  { symbol: 'LOW', name: 'Lowe’s', group: 'Health care' },
  { symbol: 'COST', name: 'Costco', group: 'Health care' },
  { symbol: 'WMT', name: 'Walmart', group: 'Consumer / travel' },
  { symbol: 'TGT', name: 'Target', group: 'Consumer / travel' },
  { symbol: 'MCD', name: 'McDonald’s', group: 'Consumer / travel' },
  { symbol: 'SBUX', name: 'Starbucks', group: 'Consumer / travel' },
  { symbol: 'NKE', name: 'Nike', group: 'Consumer / travel' },
  { symbol: 'DIS', name: 'Disney', group: 'Consumer / travel' },
  { symbol: 'CMG', name: 'CMG', group: 'Consumer / travel' },
  { symbol: 'BKNG', name: 'BKNG', group: 'Consumer / travel' },
  { symbol: 'MAR', name: 'MAR', group: 'Consumer / travel' },
  { symbol: 'RCL', name: 'RCL', group: 'Consumer / travel' },
  { symbol: 'CCL', name: 'CCL', group: 'Consumer / travel' },
  { symbol: 'GM', name: 'GM', group: 'Consumer / travel' },
  { symbol: 'F', name: 'F', group: 'Consumer / travel' },
  { symbol: 'FDX', name: 'FDX', group: 'Consumer / travel' },
  { symbol: 'UPS', name: 'UPS', group: 'Consumer / travel' },
  { symbol: 'CAT', name: 'Caterpillar', group: 'Consumer / travel' },
  { symbol: 'DE', name: 'Deere', group: 'Industrials / materials' },
  { symbol: 'HON', name: 'HON', group: 'Industrials / materials' },
  { symbol: 'GE', name: 'GE Aerospace', group: 'Industrials / materials' },
  { symbol: 'BA', name: 'Boeing', group: 'Industrials / materials' },
  { symbol: 'LMT', name: 'Lockheed Martin', group: 'Industrials / materials' },
  { symbol: 'RTX', name: 'RTX', group: 'Industrials / materials' },
  { symbol: 'NOC', name: 'NOC', group: 'Industrials / materials' },
  { symbol: 'UNP', name: 'UNP', group: 'Industrials / materials' },
  { symbol: 'CSX', name: 'CSX', group: 'Industrials / materials' },
  { symbol: 'LIN', name: 'LIN', group: 'Industrials / materials' },
  { symbol: 'APD', name: 'APD', group: 'Industrials / materials' },
  { symbol: 'SHW', name: 'SHW', group: 'Industrials / materials' },
  { symbol: 'FCX', name: 'FCX', group: 'Industrials / materials' },
  { symbol: 'NEM', name: 'NEM', group: 'Defensive / telecom' },
  { symbol: 'NUE', name: 'NUE', group: 'Defensive / telecom' },
  { symbol: 'CLF', name: 'CLF', group: 'Defensive / telecom' },
  { symbol: 'PG', name: 'Procter & Gamble', group: 'Defensive / telecom' },
  { symbol: 'KO', name: 'Coca-Cola', group: 'Defensive / telecom' },
  { symbol: 'PEP', name: 'PepsiCo', group: 'Defensive / telecom' },
  { symbol: 'MDLZ', name: 'MDLZ', group: 'Defensive / telecom' },
  { symbol: 'MO', name: 'MO', group: 'Defensive / telecom' },
  { symbol: 'PM', name: 'PM', group: 'Defensive / telecom' },
  { symbol: 'KMB', name: 'KMB', group: 'Defensive / telecom' },
  { symbol: 'CL', name: 'CL', group: 'Defensive / telecom' },
  { symbol: 'WBA', name: 'WBA', group: 'Defensive / telecom' },
  { symbol: 'T', name: 'AT&T', group: 'Defensive / telecom' },
  { symbol: 'SMCI', name: 'Super Micro Computer', group: 'Technology / growth' },
  { symbol: 'ARM', name: 'ARM', group: 'Technology / growth' },
  { symbol: 'ETN', name: 'ETN', group: 'Technology / growth' },
  { symbol: 'ANET', name: 'ANET', group: 'Technology / growth' },
  { symbol: 'ZS', name: 'ZS', group: 'Technology / growth' },
  { symbol: 'TEAM', name: 'TEAM', group: 'Technology / growth' },
]

export function getUniverseSymbols() {
  return LIQUID_OPTIONS_UNIVERSE.map((item) => item.symbol)
}
