export const scannerRun = {
  "generatedAt": "2026-07-22T12:01:00.057178+00:00",
  "source": "Expanded top100 technical indicator feed via /opt/data/scripts/mean_reversion_trades.py",
  "recommendations": [
    {
      "symbol": "BA",
      "signal": "BULLISH_REVERSION",
      "direction": "Bullish bounce",
      "score": 7.5,
      "structure": "CALL_DEBIT_SPREAD",
      "expiry": "2026-08-21",
      "dte": 30,
      "close": 204.8,
      "target": 218.93,
      "invalidation": 209.0,
      "rsi14": 34.9,
      "reasoning": "RSI washed out at 34.9 | Price is at/below lower Bollinger Band | Price is below EMA21/SMA20 and eligible for mean reversion | Close is near support (-2.0% above support)",
      "warnings": "ADX 13.4 is low/moderate; reversion setup is less trend-opposed"
    },
    {
      "symbol": "TBB",
      "signal": "BULLISH_REVERSION",
      "direction": "Bullish bounce",
      "score": 7.0,
      "structure": "CALL_DEBIT_SPREAD",
      "expiry": "2026-08-21",
      "dte": 30,
      "close": 20.18,
      "target": 20.55,
      "invalidation": 20.4,
      "rsi14": 30.8,
      "reasoning": "RSI washed out at 30.8 | Price is at/below lower Bollinger Band | Price is below EMA21/SMA20 and eligible for mean reversion | Close is near support (-1.1% above support)",
      "warnings": ""
    },
    {
      "symbol": "CVS",
      "signal": "BEARISH_REVERSION",
      "direction": "Bearish fade",
      "score": 7.0,
      "structure": "PUT_DEBIT_SPREAD",
      "expiry": "2026-08-21",
      "dte": 30,
      "close": 110.6,
      "target": 104.85,
      "invalidation": 110.6,
      "rsi14": 74.6,
      "reasoning": "RSI extended at 74.6 | Price is at/above upper Bollinger Band | Price is above EMA21/SMA20 and eligible for fade | Close is near resistance (0.0% below resistance)",
      "warnings": ""
    },
    {
      "symbol": "ISRG",
      "signal": "BULLISH_REVERSION",
      "direction": "Bullish bounce",
      "score": 7.0,
      "structure": "CALL_DEBIT_SPREAD",
      "expiry": "2026-08-21",
      "dte": 30,
      "close": 350.06,
      "target": 398.08,
      "invalidation": 345.42,
      "rsi14": 32.6,
      "reasoning": "RSI washed out at 32.6 | Price is at/below lower Bollinger Band | Price is below EMA21/SMA20 and eligible for mean reversion | Close is near support (1.3% above support)",
      "warnings": ""
    },
    {
      "symbol": "MCD",
      "signal": "BULLISH_REVERSION",
      "direction": "Bullish bounce",
      "score": 6.0,
      "structure": "CALL_DEBIT_SPREAD",
      "expiry": "2026-08-21",
      "dte": 30,
      "close": 263.91,
      "target": 271.88,
      "invalidation": 263.91,
      "rsi14": 39.3,
      "reasoning": "RSI washed out at 39.3 | Price is stretched toward lower Bollinger Band | Price is below EMA21/SMA20 and eligible for mean reversion | Close is near support (0.0% above support)",
      "warnings": "ADX 14.4 is low/moderate; reversion setup is less trend-opposed"
    },
    {
      "symbol": "PEP",
      "signal": "BULLISH_REVERSION",
      "direction": "Bullish bounce",
      "score": 6.0,
      "structure": "CALL_DEBIT_SPREAD",
      "expiry": "2026-08-21",
      "dte": 30,
      "close": 135.0,
      "target": 139.35,
      "invalidation": 135.0,
      "rsi14": 40.0,
      "reasoning": "RSI washed out at 40.0 | Price is stretched toward lower Bollinger Band | Price is below EMA21/SMA20 and eligible for mean reversion | Close is near support (0.0% above support)",
      "warnings": "ADX 18.0 is low/moderate; reversion setup is less trend-opposed"
    },
    {
      "symbol": "DHR",
      "signal": "BULLISH_REVERSION",
      "direction": "Bullish bounce",
      "score": 6.0,
      "structure": "CALL_DEBIT_SPREAD",
      "expiry": "2026-08-21",
      "dte": 30,
      "close": 179.01,
      "target": 194.74,
      "invalidation": 161.91,
      "rsi14": 37.8,
      "reasoning": "RSI washed out at 37.8 | Price is at/below lower Bollinger Band | Price is below EMA21/SMA20 and eligible for mean reversion",
      "warnings": ""
    },
    {
      "symbol": "NFLX",
      "signal": "BULLISH_REVERSION",
      "direction": "Bullish bounce",
      "score": 5.5,
      "structure": "CALL_DEBIT_SPREAD",
      "expiry": "2026-08-21",
      "dte": 30,
      "close": 68.67,
      "target": 73.18,
      "invalidation": 67.6,
      "rsi14": 32.4,
      "reasoning": "RSI washed out at 32.4 | Price is stretched toward lower Bollinger Band | Price is below EMA21/SMA20 and eligible for mean reversion | Close is near support (1.6% above support)",
      "warnings": ""
    }
  ]
}
